[package]
name = "swget"
version = "0.1.0"
authors = ["TA Thanh Dinh <tathanhdinh@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "*"
indicatif = "*"
rayon = "*"
structopt = "*"
strum = "*"
strum_macros = "*"
lazy_static = "*"
failure = "*"
